config/routes.rb
Products::Application.routes.draw do

match "/products" => 'products#index'

resources :products do
  resources :comments
end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true

  has_many :products, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author, :content, :product_id

  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :pricing, :category_id

  validates :description, :name, :pricing, presence: true

  belongs_to :category
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @Category = Category.all
  end

  def new
    @Category = Category.new
  end

  def edit
    @Category = Category.find(params[:id])
  end

  def create
     @Category = Category.new(params[:category])
     if @Category.save
      flash[:success] = "Category has been created."
      redirect_to @Category
     else
      flash.now[:errors] = @Category.errors.full_messages
      flash.keep
      @errors = @Category.errors.full_messages
      render action: "new"
     end 
  end

  def destroy
    @Category = Category.find(params[:id])
  end

  def update
    @Category = Category.find(params[:id])
  end

  def show
    @Category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @Comment = Comment.new
    @Product = Product.find(params[:product_id])
  end

  def index
    @Comment = Comment.all
  end

  def show
    @Comment = Comment.find(params[:id])
  end

  def edit
    @Comment = Comment.find(params[:id])
  end

  def create
    @Comment = Comment.new(params[:comment])
    @Product = Product.find(params[:product_id])
    if @Comment.save
      flash[:success] = "Comment has been added."
      redirect_to product_path(@Product)
    # else
    #   flash.now[:errors] = @Category.errors.full_messages
    #   flash.keep
    #   @errors = @Category.errors.full_messages
    #   render action: "new"
    end 
  end


  def destroy
    @Comment = Comment.find(params[:id])
  end

  def update
    @Comment = Comment.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @Product = Product.all
  end

  def show
    @Product = Product.find(params[:id])
    @Products = Product.all
    @Comment = Comment.all
    @Comments = Product.find(params[:id]).comments
  end

  def new
    @Product = Product.new
  end

  def edit
    @Product = Product.find(params[:id])
  end

  def create
    @Product = Product.new(params[:product])
    if @Product.save
      flash[:success] = "Product has been successfully added!"
      redirect_to @Product
    else
      flash.now[:errors] = @Product.errors.full_messages
      flash.keep
      @errors = @Product.errors.full_messages
      render action: "new"
    end   
  end

  def update
    @Product = Product.find(params[:id])

    if @Product.update_attributes(params[:product])
      flash[:message] = "Product has been sucessfully updated."
      redirect_to @Product, notice: "Product updated!"
    else
      render @User  
    end
  end

  def destroy
    @Product = Product.find(params[:id])

    if @Product.destroy
      redirect_to "/products", notice: "Product #{@Product.name} has been deleted."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

<div class = "container">

<h1>Edit Category</h1>

<% if defined? flash %>
	<% if flash[:success] %>
		<p><%= flash[:success] %></p>
	<% elsif flash[:errors] %>
		<% flash[:errors].each do |error| %>
		    <p><%= error %></p>
		   <% end %>
	<% end %>
<% end %>

	<%= simple_form_for @Category do |c| %>
	<%= c.input :name %>
	<%= c.button  :submit, class: "btn btn-primary" %>
	<% end %>
</div>

app/views/categories/index.html.erb
<div class="container">

<h1>All Categories</h1>

	<table class="table">
		<tr>
			<th>Category Name</th>
		<% @Category.each do |c| %>	
		<tr>
			<td><%="#{c.name}"%></td>
			<td><%= link_to 'Edit', edit_category_path(c.id) %></td>
			<td><%= button_to 'Delete', c, method: :delete %></td>
		</tr>	
		<% end %>
	</table>	

</div>

app/views/categories/new.html.erb
<div class = "container">

<h1>Add a New Category</h1>

<% if defined? flash %>
	<% if flash[:success] %>
		<p><%= flash[:success] %></p>
	<% elsif flash[:errors] %>
		<% flash[:errors].each do |error| %>
		    <p><%= error %></p>
		   <% end %>
	<% end %>
<% end %>

	<%= simple_form_for @Category do |c| %>
	<%= c.input :name %>
	<%= c.button  :submit, class: "btn btn-primary" %>
	<% end %>
</div>

app/views/categories/show.html.erb
<h2>Category: <%= @Category.name %></h2>

<p>
	<% if defined? flash %>
	<%= flash[:message] %>
	<% end %>
</p>

<p>
	<% if defined? notice %>
	<%= notice %>
	<% end %>
</p>	

<%= @Category.name %> <br>

<p><%= link_to "Edit Category", edit_category_path %></p>
<p><%= link_to "Delete Category", new_category_path %></p>
<p><%= link_to "Show All Categories", categories_path %></p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<div class = "container">

	<h1>Add a New Comment</h1>

		<%= simple_form_for [@Product, @Comment] do |comment| %>
		<%= comment.input :content %>
		<%= comment.input :author %>
		<%= comment.input :product_id, :as => :hidden, :input_html => { :value => "#{@Product.id}" } %>
		<%= comment.button  :submit, class: "btn btn-primary" %>
		<% end %>
</div>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= stylesheet_link_tag    "application", "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<div class = "container">

<h1>Edit Product</h1>

<% if defined? flash %>
	<% if flash[:success] %>
		<p><%= flash[:success] %></p>
	<% elsif flash[:errors] %>
		<% flash[:errors].each do |error| %>
		    <p><%= error %></p>
		   <% end %>
	<% end %>
<% end %>

	<%= simple_form_for @Product do |product| %>
	<%= product.input :name %>
	<%= product.association :category, as: :select, include_blank: false %>	
	<%= product.input :description %>
	<%= product.input :pricing %>
	<%= product.button  :submit, class: "btn btn-primary" %>
	<% end %>



</div>

app/views/products/index.html.erb
<div class="container">

<h1>List of Products</h1>

<h4><%= link_to 'Add a New Product', new_product_path %></h4>

<% if defined? notice %>
	<%= notice %>
<% end %>	

	<table class="table">
		<tr>
			<th>Product Name</th>
			<th>Category</th>
			<th>Description</th>
			<th>Price</th>
<!-- 			<th>Comment</th>
			<th>Author</th> -->
			<th>Product Info</th>
			<th>Edit</th>
			<th>Add Comment</th>
			<th>Delete</th>
		<% @Product.each do |p| %>	
		<tr>
			<td><%= p.name %></td>
			<td><%= p.category.name %></td>
			<td><%= p.description %></td>
			<td>$<%= p.pricing %></td>
<!-- 			<td><% p.comments.each do |comment| %>
			<%= comment.content %></td>
			<% end %>
			<td><% p.comments.each do |comment| %>
			<%= comment.author %></td>
			<% end %> -->
			<td><%= link_to 'Details', product_path(p.id) %></td>
			<td><%= link_to 'Edit', edit_product_path(p.id) %></td>
			<td><%= link_to 'Add Comment', "/products/#{p.id}/comments/new" %></td>
			<td><%= button_to 'Delete', p, method: :delete, class: "btn btn-small btn-danger" %></td>
		</tr>	
		<% end %>
	</table>	
</div>

app/views/products/new.html.erb
<div class = "container">

<h1>Add a New Product</h1>

<% if defined? flash %>
	<% if flash[:success] %>
		<p><%= flash[:success] %></p>
	<% elsif flash[:errors] %>
		<% flash[:errors].each do |error| %>
		    <p><%= error %></p>
		   <% end %>
	<% end %>
<% end %>

	<%= simple_form_for @Product do |p| %>  
	<%= p.input :name %>
	<%= p.association :category, as: :select, include_blank: false %>	
	<%= p.input :description %>
	<%= p.input :pricing %>
	<%= p.button  :submit, class: "btn btn-primary" %>
	<% end %>
</div>

app/views/products/show.html.erb
<div class = "container">
	<h2>Product Information</h2>

	<p><%= link_to 'Edit Product', edit_product_path %></p> <br>

	<p>
		<% if defined? flash %>
		<%= flash[:message] %>
		<% end %>
	</p>

	<p>
		<% if defined? notice %>
		<%= notice %>
		<% end %>
	</p>	
	

	<table class="table">
		<tr>
			<th>Product Name</th>
			<th>Category</th>
			<th>Description</th>
			<th>Price</th>
		</tr>
		<tr>
			<td><%= @Product.name %></td>
			<td><%= @Product.category.name %></td>
			<td><%= @Product.description %></td>
			<td><%= @Product.pricing %></td>
		</tr>	
	</table> 
	<div>

		<p><%= button_to 'Delete Product', p, method: :delete, class: "btn btn-small btn-danger" %></p> <br>

		<h4>Comments</h4>
		<table class="table">
		<!-- 	<tr>
				<th>Comment</th>
				<th>Author</th>
			</tr> -->
			<tr>
				<% @Product.comments.each do |comment| %>
				<td><%= comment.content %></td>
				<td>Posted by: <%= comment.author %></td>
				</tr>	
			<% end %>
			
		</table>
	</div>		
		<p><%= link_to 'Add Comment', new_product_comment_path(@Product.id) %></p>
		<p><%= link_to "Show All Products", products_path %></p>

</div>

<!-- 
	<%= @Product.name %> <br>
	<%= "Category: " + @Product.category.name %> <br>
	<p><%= @Product.description %> </p> <br>
	<p><%= link_to 'Add Comment', "/products/:product_id/comments/new" %></p>
	<p><%= link_to "Edit Product", edit_product_path %></p>
	<p><%= link_to "Delete Product", new_product_path %></p> -->

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>